### ISSUE TITLE
SyntaxError: invalid syntax with kafka

### ISSUE THREAD

**Issue by alberttwong** [DisasterAWARE/aws-glue-schema-registry-python#22]
```
[ec2-user@ip-172-31-19-191 aws-glue-schema-registry-python]$ python test.py
Traceback (most recent call last):
  File "/home/ec2-user/aws-glue-schema-registry-python/test.py", line 14, in <module>
    from aws_schema_registry.adapter.kafka import KafkaSerializer
  File "/home/ec2-user/.local/lib/python3.9/site-packages/aws_schema_registry/adapter/kafka.py", line 6, in <module>
    from kafka.serializer import Serializer, Deserializer
  File "/home/ec2-user/.local/lib/python3.9/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/ec2-user/.local/lib/python3.9/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/ec2-user/.local/lib/python3.9/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[ec2-user@ip-172-31-19-191 aws-glue-schema-registry-python]$ pip install kafka-python
Defaulting to user installation because normal site-packages is not writeable
Collecting kafka-python
  Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
     |████████████████████████████████| 246 kB 4.5 MB/s            
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2
[ec2-user@ip-172-31-19-191 aws-glue-schema-registry-python]$ python test.py
Traceback (most recent call last):
  File "/home/ec2-user/aws-glue-schema-registry-python/test.py", line 25, in <module>
    producer = KafkaProducer(value_serializer=seri
```

**Comment by alberttwong** [comment]
needed to install kafka-python
